# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build Docs

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
       
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Determine version
        id: version
        run: |
          export VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo "version=$VERSION" >> $>> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm i -g @koumoul/gh-pages-multi
      - run: |
          git config --global user.email "vsds@noreply.com"
          git config --global user.name "VSDS"
          git config --global url.https://${{ env.PAT }}@github.com/.insteadOf https://github.com/
        env:
          PAT: ${{secrets.PAT}}
      - run: |
          gh-pages-multi deploy --title "TEST" -t ${{steps.version.outputs.version}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
