# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
env:
  base_url: /gh-pages-multi

jobs:
       
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g @yalz/gh-pages-multi
      - run: |
          git config --global user.email "vsds@noreply.com"
          git config --global user.name "VSDS CI"
          git config --global url.https://${{ env.PAT }}@github.com/.insteadOf https://github.com/
        env:
          PAT: ${{secrets.PAT}}
      - run: |
          gh-pages-multi deploy --title "TEST" -t ${{ github.event.inputs.version }} -s docs
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
